### ISSUE TITLE
Ayuda con ouo.io.php

### ISSUE THREAD

**Issue by joelmiguelvalente** [parzibyte/ejemplo-acortadores-php#1]
Hola, tengo un problema! He usado esto de manera local (localhost en xampp) y funciona a la perfección, genera el link acortado como debe ser, pero el problema surge cuando lo coloco en una web me tira este error
`Fatal error: Uncaught Exception: Enlace inesperado al acortar con ouo.io: in /home/vilocjmf/public_html/inc/php/ajax/ajax.generador.php:56 Stack trace: #0 /home/vilocjmf/public_html/inc/php/ajax_files.php(49): include() #1 {main} thrown in /home/vilocjmf/public_html/inc/php/ajax/ajax.generador.php on line 56` y la línea 56 es `throw new Exception` en ambos casos usando la mismo api y url

**Comment by parzibyte** [comment]
Hola. No atiendo peticiones por este medio, puede contactarme aquí: https://parzibyte.me#contacto
